"""
nl_parser.py — Natural language → PromptSpec via Claude API.

Takes a scientist's plain-English request (plus conversation history and an
optional uploaded PDB) and returns a validated PromptSpec dataclass that the
prompt_builder can translate into an ESMProtein object for ESM3 generation.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Any

# ── PromptSpec dataclass ───────────────────────────────────────────────────────

@dataclass
class PromptSpec:
    """Structured specification parsed from a scientist's natural-language request."""

    protein_length: int = 100
    """Total length of the protein to generate."""

    sequence_template: str = ""
    """
    Sequence string of length `protein_length`.
    Known/fixed AAs at their positions; '_' everywhere else.
    E.g. "____MKTII_____________" — the underscores will be generated by ESM3.
    Empty string means fully masked (de novo generation).
    """

    fixed_positions: dict[int, str] = field(default_factory=dict)
    """
    Mapping of {0-based residue index: single-letter AA} for positions to keep fixed.
    Derived from sequence_template but stored separately for clarity.
    """

    function_keywords: list[str] = field(default_factory=list)
    """
    InterPro-based biological function descriptors.
    E.g. ["fluorescence", "beta barrel", "serine protease activity"]
    """

    use_structure_motif: bool = False
    """Whether a structural motif (from an uploaded PDB) should be applied."""

    motif_residue_indices: list[int] = field(default_factory=list)
    """
    0-based indices in the generated protein where backbone coordinates from the
    uploaded PDB should be placed. Maps 1-to-1 to the PDB residues in order.
    """

    motif_chain_id: str | None = None
    """PDB chain to extract motif residues from. None = first/all chains."""

    num_candidates: int = 8
    """Number of candidate proteins to generate."""

    generation_temperature: float = 0.7
    """Sampling temperature for ESM3 generation (0.0 = deterministic, 1.0 = diverse)."""

    num_steps: int = 8
    """Number of iterative unmasking steps for ESM3 generation."""

    notes_to_user: str = ""
    """Claude's explanation of how it interpreted the request."""


# ── System prompt ──────────────────────────────────────────────────────────────

_SYSTEM_PROMPT = """You are an expert protein engineering assistant that helps scientists design proteins using ESM3, a multimodal generative protein language model.

Your job is to translate the scientist's plain-English request into a structured JSON prompt specification (PromptSpec) that the software will use to configure ESM3.

## ESM3 Capabilities (what you can specify)

ESM3 reasons over three tracks simultaneously. For v1 of this tool, you can use:

### 1. Sequence masking
Specify which amino acid residues to keep fixed and which to generate.
- Fixed positions: residues the scientist wants preserved exactly
- Masked positions: positions ESM3 will generate (represented as '_')
- Positions are 0-indexed

### 2. Function keywords
High-level biological descriptors that guide ESM3 toward proteins with desired functions.
These come from InterPro annotations. Examples:
- Fluorescence: "fluorescence", "green fluorescent protein", "chromophore"
- Enzymes: "serine protease activity", "kinase activity", "oxidoreductase activity"
- Binding: "DNA binding", "zinc finger", "calcium binding", "ATP binding"
- Structure: "beta barrel", "TIM barrel", "alpha/beta hydrolase", "immunoglobulin fold"
- Transport: "MFS transporter", "ion channel"
Use specific InterPro-style terms. You can include 1-5 keywords.

### 3. Structure motif (if a PDB file is uploaded)
Preserve backbone atomic coordinates (N, CA, C, O) of specific residues.
Used to maintain an active site, binding pocket, or catalytic triad in 3D space.
Specify which residue indices in the GENERATED protein (0-based) should have their
backbone coordinates fixed to the PDB motif.

## Output format

Respond ONLY with a valid JSON object matching this schema:

```json
{
  "protein_length": <integer, e.g. 229>,
  "sequence_template": "<string of length protein_length; known AAs at fixed positions, '_' elsewhere; empty string for fully de novo>",
  "fixed_positions": {"<0-based index as string>": "<single-letter AA>", ...},
  "function_keywords": ["<keyword1>", "<keyword2>", ...],
  "use_structure_motif": <true|false>,
  "motif_residue_indices": [<0-based int>, ...],
  "motif_chain_id": "<chain letter or null>",
  "num_candidates": <integer 1-10>,
  "generation_temperature": <float 0.3-1.0>,
  "num_steps": <integer 4-20>,
  "notes_to_user": "<friendly explanation of what you inferred and any assumptions you made>"
}
```

## Rules

1. If the scientist mentions specific residue positions (e.g. "T65, Y66" or "positions 58-71"), add them to fixed_positions. Use 0-based indexing (convert from 1-based if the scientist uses 1-based numbering).

2. If they describe a desired function (e.g. "make it fluorescent", "binding to DNA"), map to the most appropriate InterPro-style keywords.

3. If a PDB file was uploaded and the scientist wants to preserve a structural motif, set use_structure_motif=true and list the 0-based indices in the GENERATED protein where those coordinates should apply.

4. Be conservative: if you're unsure whether to fix a position, mask it (let ESM3 generate it).

5. For protein_length: if the scientist specifies a length, use it. Otherwise, infer from the sequence they provide, or use a sensible default for the protein family (e.g. ~229 for GFP, ~223 for trypsin).

6. generation_temperature: 0.3–0.5 for conservative/high-fidelity designs; 0.7–1.0 for diverse/exploratory.

7. sequence_template must be exactly protein_length characters long. If empty (de novo), return "".

8. notes_to_user should be friendly and explain: what constraints you applied, any assumptions, and what the scientist should look out for.

9. Return ONLY the JSON — no markdown fences, no extra text before or after.

## Examples

### Example 1 — GFP chromophore preservation
Scientist: "Generate GFP variants. Keep the chromophore residues T65, Y66, G67, R96, E222 fixed. Also preserve the structure of the beta barrel region from residues 58 to 71. I want high fluorescence and diversity. 8 candidates."

```json
{
  "protein_length": 229,
  "sequence_template": "________________________________________________________XXXXXXXXXX__TYG________________________________R______________________________________________E___________",
  "fixed_positions": {"64": "T", "65": "Y", "66": "G", "95": "R", "221": "E"},
  "function_keywords": ["fluorescence", "beta barrel", "chromophore"],
  "use_structure_motif": true,
  "motif_residue_indices": [57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
  "motif_chain_id": null,
  "num_candidates": 8,
  "generation_temperature": 0.8,
  "num_steps": 10,
  "notes_to_user": "I'm fixing chromophore residues T65, Y66, G67 (0-indexed: 64,65,66), R96→95, E222→221. Structure motif applied to residues 58-71 (0-indexed 57-70) to preserve the beta barrel scaffold. High temperature (0.8) for diversity. Note: the full sequence_template will need your reference sequence at fixed positions."
}
```

### Example 2 — De novo serine protease
Scientist: "Design a compact serine protease with a classic catalytic triad. About 150 residues. Generate 6 candidates."

```json
{
  "protein_length": 150,
  "sequence_template": "",
  "fixed_positions": {},
  "function_keywords": ["serine protease activity", "trypsin fold", "catalytic triad"],
  "use_structure_motif": false,
  "motif_residue_indices": [],
  "motif_chain_id": null,
  "num_candidates": 6,
  "generation_temperature": 0.7,
  "num_steps": 8,
  "notes_to_user": "Fully de novo generation with function keywords guiding ESM3 toward a serine protease fold. No fixed sequence positions — ESM3 will design everything. 150 residues is compact for a protease; I'm using moderate temperature for a balance of quality and diversity."
}
```

### Example 3 — Zinc finger with preserved binding residues
Scientist: "Take this zinc finger sequence YKCEECGKSFSQKSDLVRHQRTHTG and redesign the scaffold while keeping the four zinc-coordinating cysteines at positions 3, 6, 20, 23. Upload the PDB for structural constraints."

```json
{
  "protein_length": 25,
  "sequence_template": "__C__C______________C__C_",
  "fixed_positions": {"2": "C", "5": "C", "19": "C", "22": "C"},
  "function_keywords": ["zinc finger", "zinc binding", "DNA binding"],
  "use_structure_motif": true,
  "motif_residue_indices": [2, 5, 19, 22],
  "motif_chain_id": null,
  "num_candidates": 8,
  "generation_temperature": 0.6,
  "num_steps": 8,
  "notes_to_user": "Fixing four Cys residues at 0-based positions 2, 5, 19, 22 (1-based: 3, 6, 20, 23). All other positions masked for redesign. Lower temperature (0.6) for conservative scaffold while keeping zinc coordination geometry from the PDB."
}
```
"""

# ── Parser class ───────────────────────────────────────────────────────────────

class NLParser:
    """
    Translates plain-English scientist prompts into PromptSpec objects via Claude.
    """

    MODEL = "claude-sonnet-4-6"
    MAX_TOKENS = 1024

    def __init__(self, anthropic_client=None):
        if anthropic_client is None:
            from config import get_anthropic_client
            anthropic_client = get_anthropic_client()
        self._client = anthropic_client

    def parse(
        self,
        user_message: str,
        conversation_history: list[dict[str, str]] | None = None,
        pdb_uploaded: bool = False,
        pdb_filename: str | None = None,
    ) -> PromptSpec:
        """
        Parse a scientist's message into a PromptSpec.

        Args:
            user_message:         The scientist's latest natural-language request.
            conversation_history: Previous turns as list of {"role": ..., "content": ...}
                                  dicts. Last 6 messages are included for context.
            pdb_uploaded:         Whether a PDB file has been uploaded this session.
            pdb_filename:         Name of the uploaded PDB file (for context).

        Returns:
            Parsed and validated PromptSpec.

        Raises:
            ValueError: If Claude returns malformed JSON that cannot be parsed.
        """
        messages = self._build_messages(
            user_message, conversation_history, pdb_uploaded, pdb_filename
        )

        response = self._client.messages.create(
            model=self.MODEL,
            max_tokens=self.MAX_TOKENS,
            system=_SYSTEM_PROMPT,
            messages=messages,
        )

        raw_text = response.content[0].text.strip()
        return self._parse_response(raw_text)

    def _build_messages(
        self,
        user_message: str,
        history: list[dict] | None,
        pdb_uploaded: bool,
        pdb_filename: str | None,
    ) -> list[dict]:
        messages = []

        # Include up to the last 6 history messages for context
        if history:
            for msg in history[-6:]:
                if msg.get("role") in ("user", "assistant") and msg.get("content"):
                    messages.append({"role": msg["role"], "content": msg["content"]})

        # Annotate the current message with PDB context if applicable
        content = user_message
        if pdb_uploaded:
            fname = f" ({pdb_filename})" if pdb_filename else ""
            content = (
                f"[A PDB file{fname} has been uploaded and is available for structural motif extraction.]\n\n"
                + content
            )

        messages.append({"role": "user", "content": content})
        return messages

    def _parse_response(self, raw_text: str) -> PromptSpec:
        """Parse Claude's JSON response into a PromptSpec, with validation."""
        # Strip any accidental markdown fences
        cleaned = re.sub(r"^```(?:json)?\s*", "", raw_text, flags=re.MULTILINE)
        cleaned = re.sub(r"\s*```$", "", cleaned, flags=re.MULTILINE).strip()

        try:
            data: dict[str, Any] = json.loads(cleaned)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"Claude returned invalid JSON. Raw response:\n{raw_text}\n\nError: {e}"
            )

        return self._dict_to_spec(data)

    def _dict_to_spec(self, data: dict[str, Any]) -> PromptSpec:
        """Convert a parsed JSON dict into a validated PromptSpec."""

        protein_length = int(data.get("protein_length", 100))
        protein_length = max(10, min(protein_length, 2048))  # sanity bounds

        sequence_template = str(data.get("sequence_template", ""))
        # If template provided, ensure it matches protein_length
        if sequence_template and len(sequence_template) != protein_length:
            # Pad or trim to match
            if len(sequence_template) < protein_length:
                sequence_template = sequence_template + "_" * (protein_length - len(sequence_template))
            else:
                sequence_template = sequence_template[:protein_length]

        # fixed_positions: keys may be strings (JSON) or ints
        raw_fixed = data.get("fixed_positions", {})
        fixed_positions: dict[int, str] = {}
        for k, v in raw_fixed.items():
            try:
                idx = int(k)
                aa = str(v).upper()[:1]
                if aa and 0 <= idx < protein_length:
                    fixed_positions[idx] = aa
            except (ValueError, TypeError):
                pass

        # If sequence_template is empty but fixed_positions exist, build template
        if not sequence_template and fixed_positions:
            seq = ["_"] * protein_length
            for idx, aa in fixed_positions.items():
                seq[idx] = aa
            sequence_template = "".join(seq)

        function_keywords = [str(kw) for kw in data.get("function_keywords", [])][:5]

        use_structure_motif = bool(data.get("use_structure_motif", False))

        motif_residue_indices = [
            int(i) for i in data.get("motif_residue_indices", [])
            if 0 <= int(i) < protein_length
        ]

        motif_chain_id = data.get("motif_chain_id") or None
        if isinstance(motif_chain_id, str) and motif_chain_id.strip():
            motif_chain_id = motif_chain_id.strip()
        else:
            motif_chain_id = None

        num_candidates = int(data.get("num_candidates", 8))
        num_candidates = max(1, min(num_candidates, 10))

        generation_temperature = float(data.get("generation_temperature", 0.7))
        generation_temperature = max(0.1, min(generation_temperature, 1.5))

        num_steps = int(data.get("num_steps", 8))
        num_steps = max(4, min(num_steps, 32))

        notes_to_user = str(data.get("notes_to_user", ""))

        return PromptSpec(
            protein_length=protein_length,
            sequence_template=sequence_template,
            fixed_positions=fixed_positions,
            function_keywords=function_keywords,
            use_structure_motif=use_structure_motif,
            motif_residue_indices=motif_residue_indices,
            motif_chain_id=motif_chain_id,
            num_candidates=num_candidates,
            generation_temperature=generation_temperature,
            num_steps=num_steps,
            notes_to_user=notes_to_user,
        )
