"""
ui/refinement_panel.py — Per-candidate refinement controls.

Renders the "Refine this candidate" panel beneath each top-5 result.
The scientist can configure exactly how the next generation round should
differ before submitting — implementing chain-of-thought iteration.
"""

from __future__ import annotations

import streamlit as st

from core.refiner import RefineOptions


# InterPro keyword suggestions grouped by improvement goal
_KEYWORD_SUGGESTIONS: dict[str, list[str]] = {
    "Higher activity": [
        "enhanced catalytic activity",
        "high turnover rate",
        "improved substrate binding",
        "optimised active site geometry",
    ],
    "Better stability": [
        "thermostable",
        "high thermostability",
        "salt-tolerant",
        "protease resistant",
        "improved hydrophobic core packing",
    ],
    "Better expression": [
        "soluble expression",
        "reduced aggregation propensity",
        "cytoplasmic protein",
    ],
    "Stronger binding": [
        "high affinity binding",
        "tight substrate binding",
        "improved binding pocket",
    ],
    "Novel function": [
        "broadened substrate specificity",
        "altered ligand specificity",
        "gain of function",
    ],
}


def render_refinement_panel(
    candidate: "CandidateResult",
    original_spec: "PromptSpec",
    round_num: int,
    panel_key: str,
) -> RefineOptions | None:
    """
    Render the full refinement configuration panel for one candidate.

    Args:
        candidate:    The candidate to refine from.
        original_spec: The PromptSpec that generated this candidate.
        round_num:    Current generation round number (for display).
        panel_key:    Unique key suffix to avoid Streamlit widget key clashes.

    Returns:
        RefineOptions if the user clicked "Generate refined candidates",
        None otherwise.
    """
    with st.container():
        st.markdown(f"#### 🔬 Refine Candidate #{candidate.rank}")
        st.caption(
            f"Starting from: pTM={candidate.ptm:.3f} · "
            f"pLDDT={candidate.mean_plddt:.1f} · "
            f"ESM2={candidate.esm2_score:.3f} · "
            f"length={len(candidate.sequence)} aa"
        )

        # ── Section 1: Confidence threshold ────────────────────────────────────
        st.markdown("**1. What to keep fixed vs. regenerate**")
        st.caption(
            "Residues with pLDDT above the threshold are kept fixed. "
            "Lower-confidence regions are regenerated by ESM3."
        )

        col_thresh, col_info = st.columns([2, 1])
        with col_thresh:
            plddt_threshold = st.slider(
                "Fix residues with pLDDT ≥",
                min_value=0.0,
                max_value=100.0,
                value=70.0,
                step=5.0,
                key=f"plddt_thresh_{panel_key}",
                help="Higher = keep more positions fixed (conservative). Lower = regenerate more (exploratory).",
            )

        with col_info:
            if candidate.plddt_per_residue:
                plddt_arr = candidate.plddt_per_residue
                if max(plddt_arr) <= 1.0:
                    plddt_arr = [v * 100.0 for v in plddt_arr]
                n_fixed = sum(1 for v in plddt_arr if v >= plddt_threshold)
                n_masked = len(plddt_arr) - n_fixed
                st.metric("Fixed", n_fixed, delta=None)
                st.metric("Regenerated", n_masked, delta=None)
            else:
                st.info("pLDDT not available — all positions will be regenerated.", icon="ℹ️")

        st.markdown("---")

        # ── Section 2: Function keywords ───────────────────────────────────────
        st.markdown("**2. Add function keywords** _(optional)_")
        st.caption(
            "These are added to the existing keywords from the previous round. "
            "Use InterPro-style terms to steer ESM3 toward specific improvements."
        )

        # Suggestion selector
        goal_group = st.selectbox(
            "Quick-add by improvement goal",
            options=["— Select —"] + list(_KEYWORD_SUGGESTIONS.keys()),
            key=f"kw_goal_{panel_key}",
        )

        suggested_kws: list[str] = []
        if goal_group and goal_group != "— Select —":
            suggested_kws = _KEYWORD_SUGGESTIONS[goal_group]
            selected_suggested = st.multiselect(
                f"Select keywords from '{goal_group}'",
                options=suggested_kws,
                default=[],
                key=f"kw_suggested_{panel_key}",
            )
        else:
            selected_suggested = []

        custom_kws_raw = st.text_input(
            "Or type custom keywords (comma-separated)",
            placeholder="e.g. high fluorescence intensity, thermostable",
            key=f"kw_custom_{panel_key}",
        )
        custom_kws = [k.strip() for k in custom_kws_raw.split(",") if k.strip()]
        extra_keywords = list(dict.fromkeys(selected_suggested + custom_kws))

        # Show what will be active in this round
        all_keywords = list(original_spec.function_keywords) + extra_keywords
        if all_keywords:
            st.caption(f"Active this round: `{'` · `'.join(all_keywords[:8])}`")

        st.markdown("---")

        # ── Section 3: Secondary structure hint ────────────────────────────────
        st.markdown("**3. Secondary structure hint** _(optional)_")
        st.caption(
            "Describe any secondary structure changes in plain English. "
            "E.g. 'Convert the loop at position 50–60 into an alpha helix' or "
            "'Increase beta-strand content in the C-terminal domain'."
        )
        ss8_hint = st.text_area(
            "Secondary structure instruction",
            placeholder="Leave empty to keep the current secondary structure pattern.",
            height=80,
            key=f"ss8_{panel_key}",
        )
        ss8_hint = ss8_hint.strip() or None

        st.markdown("---")

        # ── Section 4: SASA bias ───────────────────────────────────────────────
        st.markdown("**4. Surface accessibility bias** _(optional)_")
        sasa_options = [
            "No change",
            "More buried core",
            "More exposed surface",
            "Amphipathic",
        ]
        sasa_choice = st.radio(
            "Solvent-accessible surface area preference",
            options=sasa_options,
            index=0,
            horizontal=True,
            key=f"sasa_{panel_key}",
            help=(
                "Buried core → improved thermostability and hydrophobic packing. "
                "Exposed surface → better solubility. "
                "Amphipathic → membrane-active or surface-active proteins."
            ),
        )
        sasa_bias = None if sasa_choice == "No change" else sasa_choice.lower()

        st.markdown("---")

        # ── Section 5: Condensation ────────────────────────────────────────────
        st.markdown("**5. Condense scaffold** _(optional)_")
        st.caption(
            "Reduce protein length while retaining key sites and motifs. "
            "Inspired by the paper's trypsin compression (223→150 residues, −33%). "
            "ESM3 redesigns the scaffold at the target length."
        )

        condense = st.toggle(
            "Enable condensation",
            value=False,
            key=f"condense_{panel_key}",
        )

        condense_target: int | None = None
        if condense:
            current_len = len(candidate.sequence)
            min_len = max(20, len(original_spec.fixed_positions) + 10)
            default_target = max(min_len, int(current_len * 0.80))
            condense_target = st.slider(
                "Target length (residues)",
                min_value=min_len,
                max_value=current_len - 1,
                value=default_target,
                step=5,
                key=f"condense_len_{panel_key}",
                help=f"Current: {current_len} aa. Minimum (must keep active site): {min_len} aa.",
            )
            reduction_pct = (1 - condense_target / current_len) * 100
            st.caption(
                f"Reducing from {current_len} → {condense_target} residues "
                f"({reduction_pct:.0f}% reduction). "
                f"{len(original_spec.fixed_positions)} active site residues will be remapped and preserved."
            )

        st.markdown("---")

        # ── Section 6: Free-text additional instruction ────────────────────────
        st.markdown("**6. Additional instructions** _(optional)_")
        free_text = st.text_area(
            "Anything else to guide this refinement round",
            placeholder=(
                "E.g. 'Try to improve the N-terminal helix packing' or "
                "'Make it more similar to human proteins' or "
                "'Reduce hydrophobic patches on the surface'."
            ),
            height=80,
            key=f"free_text_{panel_key}",
        )
        free_text = free_text.strip()

        st.markdown("---")

        # ── Submit ─────────────────────────────────────────────────────────────
        col_btn, col_cancel = st.columns([2, 1])
        with col_btn:
            submit = st.button(
                f"🚀 Generate refined candidates from #{candidate.rank}",
                type="primary",
                use_container_width=True,
                key=f"refine_submit_{panel_key}",
            )
        with col_cancel:
            cancel = st.button(
                "Cancel",
                use_container_width=True,
                key=f"refine_cancel_{panel_key}",
            )

        if cancel:
            return None

        if submit:
            return RefineOptions(
                plddt_fix_threshold=plddt_threshold,
                extra_keywords=extra_keywords,
                ss8_hint=ss8_hint,
                sasa_bias=sasa_bias,
                condense=condense,
                condense_target_length=condense_target,
                free_text=free_text,
            )

    return None


def render_round_breadcrumb(generation_history: list[dict]):
    """
    Render a round-navigation breadcrumb trail at the top of the results panel.
    Shows Round 1 → Round 2 → ... and lets users jump back to any round.
    """
    if len(generation_history) <= 1:
        return

    st.markdown("**Generation rounds:**")
    crumbs = []
    for i, entry in enumerate(generation_history):
        round_num = entry.get("round", i + 1)
        refined_from = entry.get("refined_from")

        if refined_from is not None:
            label = f"Round {round_num} (refined from #{refined_from})"
        else:
            label = f"Round {round_num} (initial)"

        crumbs.append(label)

    # Radio selector — selecting a past round shows that round's results
    selected_label = st.radio(
        "View round:",
        options=crumbs,
        index=len(crumbs) - 1,  # default to latest round
        horizontal=True,
        key="round_selector",
        label_visibility="collapsed",
    )

    selected_idx = crumbs.index(selected_label)
    st.session_state["viewing_round"] = selected_idx
